### ISSUE TITLE
Mobile onTap bug

### ISSUE THREAD

**Issue by AlexHolly** [piskelapp/piskel#371]
Select simple pen.
1. On a single tap the draw area flashes blue.
2. On hold tap the draw area flashes blue, now you can only delete pixels.
   2.1 Tap again now you are able to draw again.

What is this blue flashing and is it possible to deactivate it?

**Comment by juliandescottes** [comment]
Maintaining a touch event on the same spot triggers a context menu. The context menu event is prevented on the drawing area, but the application still registered a mousedown/tap using the RIGHT mouse button, therefore selecting the secondary color.

By default the secondary color is transparent, which is why it "deletes" pixels. Tapping again retriggers an event for the LEFT button, which gets it back to normal.

So looks like the touch events need a bit more work. I guess we should always use the primary color in case of touch events.

Regarding the blue overlay, I guess it's the default selection overlay, don't know yet how we can deactivate it but that should be doable.

**Comment by juliandescottes** [comment]
As suspected the browser is triggering an actual mousedown event with button = 2 (right button).

The best is to preventDefault on the touchstart event. This also removes the selection overlay mentioned in the issue.

**Comment by juliandescottes** [comment]
Should be fixed with v0.7.0, released yesterday on piskelapp.com

@AlexHolly feel free to reopen if this is still occurring (I still have no way to test tablets :/ )
Thanks!

**Comment by AlexHolly** [comment]
Do I have to use the offline version? I can't see any difference on the web version. For a moment I thought this could be a feature but it can really confuse to delete with a pen on simple tap.

Where can I see the piskel version in the web version?

**Comment by juliandescottes** [comment]
It is only on http://piskelapp.com for now. https://juliandescottes.github.io/piskel has not been updated yet, and there is no app for mobile devices.

You can tell if you have the new version if there is "1a" displayed on the right of each layer in the layers list :  
![image](https://cloud.githubusercontent.com/assets/1141550/14191439/25da8c06-f798-11e5-9fbc-6fc4003994dc.png)

Using in-browser emulators, the behaviour is fine ... I'm afraid I can't do more. Would need someone who has an actual device to spend time on this. 

Reopening for now. 
@AlexHolly please confirm you have the latest version using what I said above.

**Comment by AlexHolly** [comment]
I can confirm that I tested the new version(with chrome browser).
