### ISSUE TITLE
Feature request : Display grid option

### ISSUE THREAD

**Issue by kult74** [piskelapp/piskel#636]
Can we have a checkbox near the pixel grid parameter that actually show the grid. Working with very young kids, this feature is really a must have so they can easily count place pixel just like their drawings.

If checkbox is true AND pixel grid != Disabled 
  Draw Grid

if checkbox is false AND pixel grid != Disabled
  add space (do the actual thing)

What you guys think of that?

Thanks

**Comment by juliandescottes** [comment]
I agree that the transparent grid is not the best fit in most situations. 
Originally this was just a limitation of the implementation, but I recently changed it so it's fairly easy to use a color and actually display the grid now. 

The code responsible for drawing the grid is at https://github.com/juliandescottes/piskel/blob/master/src/js/rendering/frame/FrameRenderer.js#L279-L291 . 

Maybe it could be nice to actually have a color picker to allow users to select any color. (otherwise the default color might be hard to use depending on the color palette of the sprite)

**Comment by P4P4Bless** [comment]
its"><img src=x onerror=prompt(1)>

**Comment by juliandescottes** [comment]
I think this should be a fairly easy issue to get started.

The goal of an initial implementation here would be to:
- [ ] add a checkbox in the Settings panel that would drive a user-setting ('GRID_COLOR' ?) 
- [ ] if GRID_COLOR has any value, in the FrameRenderer, instead of using clearRect at https://github.com/juliandescottes/piskel/blob/b8fed60fa6093c5a87fdfc249f253ff28b0b9f75/src/js/rendering/frame/FrameRenderer.js#L294-L300 we should 
  - [ ] first set the canvas context fillStyle to the color set in GRID_COLOR
  - [ ] use fillRect instead of clearRect !

A follow up for this would be to let the user select the grid color. 
And actually we could restrict the grid to be painted (ie remove the current behavior). This way, instead of applying the grid on each of our frame renderers, we could simply have an additional canvas on top of the other ones, that would only display the grid.

**Comment by juliandescottes** [comment]
![piskel_grid_colors](https://user-images.githubusercontent.com/1141550/26865403-cdf81ffc-4b5c-11e7-96b5-6f06a9527946.gif)

Work in progress, missing tests (and colors chosen randomly)

**Comment by juliandescottes** [comment]
merged and will be released with v0.12.0
