### ISSUE TITLE
Undo/Redo Mobile

### ISSUE THREAD

**Issue by AlexHolly** [piskelapp/piskel#662]
I am looking for an undo/redo button 

![image](https://cloud.githubusercontent.com/assets/4741886/25066630/ee1f7f64-222b-11e7-94e7-75fd11c3961c.png)

**Comment by juliandescottes** [comment]
This is definitely something we should do. 

If we detect that Piskel is used on a tablet, we should display additional controls such as the undo/redo buttons here. Other controls that come to mind are the zoom-in / zoom-out, (and cut / copy / paste , but not sure how the current selection tools can be used currently on a tablet).

I'm wondering what Piskel looks like on a typical tablet. Could someone post a screen capture so that we can see where would be the best spot to add the buttons? Maybe we could add a new set of tools in the transform box ?

**Comment by AlexHolly** [comment]
http://www.samsung.com/de/support/model/SM-P6050ZKEDBT
https://www.dropbox.com/s/uobep6vhkmrlvhk/Screenshot_2017-04-16-12-23-50.jpg?dl=0

**Comment by juliandescottes** [comment]
thanks, adding the screenshot here

![image](https://cloud.githubusercontent.com/assets/1141550/25070938/efe9a976-22aa-11e7-9956-0ff0ca7690c3.png)
