### ISSUE TITLE
1000x1000 bug

### ISSUE THREAD

**Issue by jairuspiskelmak0r** [piskelapp/piskel#668]
1000X1000 or bigger sized canvas when i drag the field of view and it erases what you can see
happens occasionally

* operating system:windows
* browser;chrome

### Sprite details
* number of frames:1
* sprite resolution:1000x1000
* session duration:0:00:10
when i drag my field of view:
![piskplace](https://cloud.githubusercontent.com/assets/28092897/25477505/568367c6-2b70-11e7-9479-581c4ab93b99.png)

**Comment by rajsite** [comment]
Nice test case :D

**Comment by juliandescottes** [comment]
Sorry, missed this bug! 

@jairuspiskelmak0r if I understand correctly from your attached image, the issue is that your drawing gets slightly shifted and you lose content. In the screenshot there is a blank space on the top and on the right, and there shouldn't be, right ?

Can't reproduce the issue, so some additional questions:
- How do you drag the field of view? Do you use:
  - the middle mouse button on the drawing area
  - the "preview rectangle" on the minimap
- Did you try to undo (ctrl+Z) after the issue happened? 
- Are you using several layers?
- Did you have the "Move" (hand) tool selected?

In case it happens again, could you open the Developer Tools of Chrome (F12). go to the Console, and see if any errors are logged there?

Thank you!

**Comment by juliandescottes** [comment]
(and yes that's an amazing piece!)

**Comment by juliandescottes** [comment]
@jairuspiskelmak0r Any additional info we could use to reproduce your issue?

**Comment by juliandescottes** [comment]
No action here.
