### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by LoneWolf8** [piskelapp/piskel#794]
Why can't the Piskel just automatically save its self instead of us manually having to save and possibly forget to save?

**Comment by juliandescottes** [comment]
Local backups performed regularly, and Piskel prompts about saving when closing the application.

When it comes to saving on the gallery, my main concern is the increase in bandwidth, CPU usage and storage, which are expensive. I'd like to keep the cost of Piskel relatively low so that I can keep the project up.

Do you have a concrete suggestion to have automatic saves without impacting costs?

**Comment by juliandescottes** [comment]
I am closing this because I don't see anything actionable. But suggestions or PRs are welcome if anybody wants to improve saving.
