### ISSUE TITLE
Piskel is very slow with Chrome 65 and OSX 10.11.6

### ISSUE THREAD

**Issue by fadedyellowroses** [piskelapp/piskel#796]
i have plenty of pieces on piskel by now, and for some reason it has started immensely lagging recently. it started when i added a piece from fire alpaca to piskel to get rid of the back ground to one i was doing, and it was lagging immensely. (i was tracing a picture someone took at their request, and wanted to use the fill all of one color tool to have it go faster, it was slower) since then, even when i took it off, deleted, and destroyed it from piskel (keeping an extra copy on my computer) it still lagged, and continues to lag today. anyhelp? like could it be just that i have too many pieces on there, or is it just old now, or is it because i added that one jpeg pic i was tracing that had thousands of colors on it cause you know. it was a jpeg.

**Comment by juliandescottes** [comment]
Hi! I need the information which is requested in the issue template to investigate:
- what is your operating system
- what is your browser (or are you using a desktop application)
- can you share a sprite where the issue happens
- what are the specs of the sprites mentionned here ?
  - resolution
  - number of layers
  - number of frames
- and since this is a performance question, a rough description of your hardware would be helpful

Adding images with a lot of colors in Piskel can definitely slow it down. But if I read correctly, now it is "always slow" ? Even if you are doing a 32x32 sprite? If that's the case it sounds like a browser or hardware issue? At least right now I can't see what would cause Piskel to lag when starting a new sprite.

A wild guess would be to say that "hardware acceleration for canvas might be disabled on your browser".

**Comment by fadedyellowroses** [comment]
1. my operating system is an osxl mac computer.
2. my browser is google.
3. it happens with all sprites
4.
resolution: i was working with a something that was well over 500x500, more height than width. but it didn't bother me for the most part because it usually lags at higher resolutions. later i was working with 24x24 and it lagged just as bad, so i deleted the gigantic pic, and didn't do anything to help. (also just gonna mention this, it had WELL over a crap ton of colors cause it was a jpeg)
number of layers: 1
frames: 1
5. i am not sure what i should say for this one.

and what do you mean by that last sentence, and how could i enable it or find out.

**Comment by juliandescottes** [comment]
That sounds really weird!

> 5. i am not sure what i should say for this one.

You said you use a mac, you can use 
![image](https://user-images.githubusercontent.com/1141550/38129217-614ff25e-33fe-11e8-8c7c-9cc68db949ea.png)
and you'll get some information that can be relevant here.

> and what do you mean by that last sentence, and how could i enable it or find out.

Now that I know you use Google Chrome I can give more details. Go to settings, scroll down, click on advanced, scroll down, and check that acceleration is enabled.

![image](https://user-images.githubusercontent.com/1141550/38129274-a24fb47e-33fe-11e8-8a89-e3ab34980eea.png)

> later i was working with 24x24 and it lagged just as bad, so i deleted the gigantic pic

To make things clear here: you were working on a 24x24 sprite, it lagged, so you went to your gallery and deleted the other sprite that was over 500 x 500 ? Sprites from the gallery cannot have any impact on each other, so you can restore it if you want. 

Could you try to use a private window in Chrome? If the lag disappears when you do that, then it means the issue is with something we locally save in the browser. It could either be:
1. a backed up sprite. 
If you go to Import >  Browse backups 
![image](https://user-images.githubusercontent.com/1141550/38129524-b230a21c-33ff-11e8-9257-7f36f11e5778.png)
You will have a popup with a list of recent sessions backed up. I can't see why this would have any impact but maybe to delete them?
2. a color palette. Normally color palettes are capped so even if you happened to create one based on your huge jpeg it should not make any difference.

**Comment by fadedyellowroses** [comment]
what info do you need about the mac?

that thing that accelerates it is enabled already.

the incognito thing doesn't work either.

i did go ahead and delete all back ups anyway, and no affect.


so i checked another computer, and it worked perfectly fine! no problems. so it might be a problem with this specific computer

**Comment by juliandescottes** [comment]
> what info do you need about the mac?

The overview info eg

![image](https://user-images.githubusercontent.com/1141550/38154863-bac32a7e-3474-11e8-955a-240102827551.png)

> the incognito thing doesn't work either.

Hmmm could you try another browser, Firefox preferably?

> so i checked another computer, and it worked perfectly fine! no problems. so it might be a problem with this specific computer

It might but since you said it worked fine before something must have changed. Maybe a Google Chrome update makes Piskel super slow on some computers? Could you try the offline version: 
https://www.piskelapp.com/download

It's is based on Chrome, but an older version. If the performance with this is good, then it's definitely a Chrome update which doesn't work well with your hardware + piskel. I'll have a look at the bugs opened on Chrome right now to see if anything seems relevant.

**Comment by juliandescottes** [comment]
(and thank you for your patience and putting up with my testing request so far, it really helps :) )

**Comment by juliandescottes** [comment]
Oh I just found https://bugs.chromium.org/p/chromium/issues/detail?id=823335&q=component%3ABlink%3ECanvas&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Looks like Chrome has a big performance issue with 2D canvas and Mac OS 10.11.6. If by any chance this is the version of OSX you are running, I think that you are affected by this Chrome bug.

**Comment by fadedyellowroses** [comment]
so do i need to un update chrome by one?

**Comment by juliandescottes** [comment]
If indeed you use OSX 10.10 or 10.11, you can try to downgrade Chrome, but I don't think that's easy. Alternatively, you can use Firefox.

**Comment by fadedyellowroses** [comment]
don't have firefox, nor do i know how to use it

**Comment by juliandescottes** [comment]
@fadedyellowroses can you confirm your version of OSX? It should be displayed in "About This Mac".

**Comment by juliandescottes** [comment]
Thanks for confirming, hope the Chrome bug at  https://bugs.chromium.org/p/chromium/issues/detail?id=823335&q=component%3ABlink%3ECanvas&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified can be resolved. 

Maybe I should add a message in the application in the meantime to encourage affected users to switch to Firefox.

**Comment by fadedyellowroses** [comment]
Yay! Your welcome!
