### ISSUE TITLE
[Feature request] Command line argument to do the export programatically

### ISSUE THREAD

**Issue by tforgione** [piskelapp/piskel#853]
First of all, thank you for this great app !

I would like to (try to) make a game and edit sprites with the desktop version of piskel, and it would be very nice for me (and perhaps others) to be able to do the export programatically.

In fact, I'd like to be able to put the .piskel files on git so I can get them and edit them from everywhere, and avoid one of the two following things:

  - put also the png files on the git
  - manually export all sprites

Having a command line tool to do the export would allow me to generate the image files just before compiling for example.

**Comment by juliandescottes** [comment]
Glad you like the app :) 

This would be a tool that would take a `.piskel` file in input and would create the `.png` spritesheet in output?
`piskel-cli my-sprite.piskel` -> creates `my-sprite.png`
Potentially with additional arguments to handle the zoom/row/column options found in the export section.

**Comment by tforgione** [comment]
Yes exaclty, something with some arguments like the options that are selected via the interface !

**Comment by jordanjwatkins** [comment]
I'm currently taking a stab at this.

So far, I've got a new 'cli' folder in the project root with an entry script that sets up and runs a phantomjs script that then loads the piskel app js (from 'dest') into a page and uses it to perform the export actions.

Rather than scripting the UI actions to export, I'm using the modules directly and avoiding or mocking out pieces that interact with UI. For example, I instantiate a PngExportController with a plain object with a single 'getExportZoom' method instead of the usual instance of ExportController.

So far the approach is working well and I can go from a piskel file to a png with auto-cropping and zoom options.

Does the direction sound alright?
